name: Rustix-test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    # Define the PostgreSQL service container
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres # Or your preferred user
          POSTGRES_PASSWORD: mypassZ # Use a strong password or GitHub Secrets in a real scenario
          POSTGRES_DB: postgres # Or your preferred database name
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $$POSTGRES_USER" # Use $$ to escape $ in YAML
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose